version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - APP_API_KEY=${APP_API_KEY}
      - DEBUG=${DEBUG}
      - FRESHDESK_DOMAIN=${FRESHDESK_DOMAIN}
      - FRESHDESK_API_KEY=${FRESHDESK_API_KEY}
      - OPENAI_SWARM_API_KEY=${OPENAI_SWARM_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
